### ISSUE TITLE
채팅방 삭제시 툴팁밀림이슈 

### ISSUE THREAD

**Issue by westkite1201** [DCNFT/digibot-frontend#23]

**Comment by SeongMyeong** [comment]
현상황: 스크롤이 위에 있는상황에서 임의의 채팅방 삭제 시 삭제된 채팅방을 기준으로 아래의 채팅방들의 모달이 삭제되기 전 채팅방들을 기준으로 위치함 -> 한번 하단으로 스크롤을 하면 제자리에 위치함

**Comment by westkite1201** [comment]
수정 완료 되었으므로 close 합니다.
