### ISSUE TITLE
신규 채팅방 생성 시 채팅방 2개 생성 이슈

### ISSUE THREAD

**Issue by SeongMyeong** [DCNFT/digibot-frontend#25]
재현빈도: 낮음

재현순서
1. "새로운 채팅" 선택
2. 신규 임의의 채팅 입력
3. 신규 채팅방 생성 후 새로고침 시 동일한 제목의 채팅방이 2개 생성
4. 하나는 채팅메시지가 있는 채팅방인데, 다른 하나는 동일한 제목에 빈 채팅방 생성됨

**Comment by westkite1201** [comment]
해당 사항 이슈 수정 후 서버에 반영하였습니다.
