### ISSUE TITLE
채팅방 해시태그 초기값 불필요데이터 확인

### ISSUE THREAD

**Issue by SeongMyeong** [DCNFT/digibot-frontend#26]
재현빈도: 자주

재현순서
1. 신규채팅방 생성
2. 해시태그 확인 -> 아무것도 없는것 확인
3. 레이어 변경
4. 해시태그 확인 -> 해시태그에 아무것도 없는 X 해시태그 발견

![image](https://github.com/DCNFT/digibot-frontend/assets/29848405/2a58bee8-d3ad-4187-be0f-3d78274f8bd0)

**Comment by westkite1201** [comment]
확인 및 수정중

**Comment by westkite1201** [comment]
#17 에서 수정완료
